- name: "update apt packages"
  apt:
    update_cache: yes

# - name: "upgrade packages"
#   apt:
#     upgrade: yes

- name: "remove dependencies that are no longer required"
  apt:
    autoremove: yes

- name: "Install Node.JS"
  become: true
  apt:
    name: ["nodejs","npm"]
    state: present
    update_cache: yes

- name: "Install zip utility."
  apt:
    name: [ "zip", "unzip" ]
    state: latest
    update_cache: yes

- name: "install pm2"
  npm:
    name: pm2
    global: yes



